{{- $adminPasswordSecret := ( lookup "v1" "Secret" .Release.Namespace .Values.adminPassword.secretKeyRef.name ) | default dict}}
{{- $adminpasswordSecretData := ( get $adminPasswordSecret "data" ) | default dict }}
{{- $adminPassword :=  (( get $adminpasswordSecretData "password") | b64dec ) | default ( randAlphaNum 12 )  }}

{{- if .Values.adminPassword.secretKeyRef.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminPassword.secretKeyRef.name }}
type: Opaque
stringData:
  password: {{$adminPassword | quote}}
{{- end}}

{{- if and (eq .Values.authProvider "basic") .Values.htpasswd.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mission-control-htpasswd
type: Opaque
stringData:
  {{ .Values.htpasswd.secretKey }}: {{ htpasswd "admin@local" $adminPassword | quote }}
{{- end}}
