apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-commander.name" . }}
  labels:
    {{- include "incident-commander.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "incident-commander.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "incident-commander.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "incident-commander.fullname" . }}-sa
      volumes:
        - name: properties-config
          configMap:
            name: {{ include "incident-commander.fullname" . }}-properties-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretKeyRef.name }}
                  key: {{ .Values.db.secretKeyRef.key }}
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.jwtSecretKeyRef.name  }}
                  key: {{ .Values.db.jwtSecretKeyRef.key }}
          envFrom:
            - secretRef:
                name: {{ .Values.smtp.secretRef.name }}
                optional: true
            - secretRef:
                name: {{ .Values.upstream.secretName }}
          command:
            - /app/incident-commander
          args:
            - serve
            - --apm-hub=http://apm-hub:8080
            - --canary-checker=http://canary-checker:8080
            - --config-db=http://config-db:8080
           {{- range $k, $v := .Values.extraArgs}}
           - --{{$k}}={{$v}}
           {{- end }}
           {{- if (tpl .Values.otel.collector .) }}
            - --otel-collector-url={{ tpl .Values.otel.collector . | default "" }}
           {{- end }}
           {{- if (tpl .Values.otel.serviceName .) }}
            - --otel-service-name={{ tpl .Values.otel.serviceName . | default "mission-control" }}
           {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
              periodSeconds: 10
              failureThreshold: 120 # 20 minutes for any migration scripts to run
              httpGet:
                path: /health
                port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          volumeMounts:
            - mountPath: /app/mission-control.properties
              name: properties-config
              subPath: mission-control.properties
      {{- with .Values.extra }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
