{{- if .Values.upstream.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.upstream.secretName }}
stringData:
  UPSTREAM_HOST: {{ .Values.upstream.host }}
  UPSTREAM_USERNAME: {{ .Values.upstream.username }}
  UPSTREAM_PASSWORD: {{ .Values.upstream.password }}
  AGENT_NAME: {{ .Values.upstream.agentName }}
{{- end }}
