{{- if not .Values.permissions.playbooks }}
---
apiVersion: mission-control.flanksource.com/v1
kind: PermissionGroup
metadata:
  name: all-notifications
spec:
  notifications:
    - name: "*"
---
apiVersion: mission-control.flanksource.com/v1
kind: Permission
metadata:
  name: allow-all-notifications-to-run-playbooks
spec:
  description: Grant all notifications to run playbooks
  subject:
    group: all-notifications
  actions:
    - "playbook:*"
  object:
    playbooks:
      - name: '*'
---
apiVersion: mission-control.flanksource.com/v1
kind: Permission
metadata:
  name: allow-all-notifications-config-component-read
spec:
  description: Grant all notifications to read configs & components
  subject:
    group: all-notifications
  actions:
    - read
  object:
    configs:
      - name: "*"
    components:
      - name: "*"    
---
apiVersion: mission-control.flanksource.com/v1
kind: Permission
metadata:
  name: allow-editors-to-run-playbooks
spec:
  description: Grant editors to run playbooks
  subject:
    group: editor
  actions:
    - "playbook:*"
  object:
    playbooks:
      - name: '*'
{{- end}}