apiVersion: canaries.flanksource.com/v1
kind: Topology
metadata:
  name: prometheus
spec:
  icon: prometheus
  type: Topology
  schedule: "@every 5m"
  components:
    - name: pods
      icon: pods
      lookup:
        kubernetes:
        - display:
            javascript: JSON.stringify(k8s.getPodTopology(results))
          kind: Pod
          name: k8s
          namespace:
            name: monitoring
      properties:
      - lookup:
          prometheus:
          - display:
              javascript: |
                var components = [];
                for (idx in results) {
                  var value = parseInt(Number(results[idx].value))
                  // CPU can be between 0 & 1, so take ceil for that case
                  if (value < 1) {value = 1}

                  components.push({
                    name: results[idx].pod,
                    properties: [{name: 'cpu', value: value}],
                  })
                }
                JSON.stringify(components)
            query: 1000 * max by (pod) (rate(container_cpu_usage_seconds_total{container!=""}[5m]))
            url: http://prometheus-k8s.monitoring:9090
        name: cpu
      - lookup:
          prometheus:
          - display:
              javascript: |
                var components = [];
                for (idx in results) {
                  components.push({
                    name: results[idx].pod,
                    properties: [{name: 'memory', value: parseInt(Number(results[idx].value))}],
                  })
                }
                JSON.stringify(components)
            query: max by (pod) (avg_over_time(container_memory_working_set_bytes{container!=""}[5m]))
            url: http://prometheus-k8s.monitoring:9090
        name: memory
    - name: Prometheus Database
      icon: prometheus
      properties:
      - name: Metrics count
        headline: true
        lookup:
          prometheus:
            - query: 'count({__name__=~".+"})'
              host: 'http://prometheus-k8s.monitoring:9090'
              display:
                expr: results[0].value
      - name: Disk used (GB)
        headline: true
        lookup:
          prometheus:
            - query: 'prometheus_tsdb_storage_blocks_bytes / (1024 * 1024 * 1024)'
              host: 'http://prometheus-k8s.monitoring:9090'
              display:
                javascript: |
                  value = ''
                  if (results.length > 0) {
                    value = results[0].value
                  }
                  value.toString().substring(0,6)
      - name: Targets
        headline: true
        lookup:
          prometheus:
            - query: 'count(prometheus_target_scrape_pool_targets)'
              host: 'http://prometheus-k8s.monitoring:9090'
              display:
                expr: results[0].value
      - name: Rule groups with duration > 1 sec
        lookup:
          prometheus:
            - query: 'count(prometheus_rule_group_last_duration_seconds > 1)'
              host: 'http://prometheus-k8s.monitoring:9090'
              display:
                expr: results[0].value
