{{- if .Values.db.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-postgres-db
  labels:
    {{- include "incident-commander.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: create-postgres-db
          image: usql/postgres
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretKeyRef.name | default "postgres-connection" }}
          command: ["bash"]
          args:
            - -c
            - echo "SELECT 'CREATE DATABASE incident_commander' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'incident_commander')\gexec" | PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER

      restartPolicy: Never
{{- end }}
