{{- if .Values.global.db.connectionPooler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "incident-commander.fullname" . }}-pgbouncer
  annotations:
{{ toYaml .Values.global.db.connectionPooler.serviceAccount.annotations | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incident-commander.fullname" . }}-pgbouncer
spec:
  selector:
    app: {{ include "incident-commander.fullname" . }}-pgbouncer
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-commander.fullname" . }}-pgbouncer
spec:
  selector:
    matchLabels:
      app: {{ include "incident-commander.fullname" . }}-pgbouncer
  template:
    metadata:
      labels:
        app: {{ include "incident-commander.fullname" . }}-pgbouncer
    spec:
      serviceAccountName: {{ include "incident-commander.fullname" . }}-pgbouncer
      containers:
      - name: pgbouncer
        image: {{ .Values.global.db.connectionPooler.image }}
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: configfiles
            mountPath: "/etc/pgbouncer/"
            readOnly: true 
{{ .Values.global.db.connectionPooler.extraContainers | indent 6 }}
      volumes:
        - name: configfiles
          secret:
            secretName: {{ include "incident-commander.name" . }}-pgbouncer-config
---
{{- end }}