{{- if .Values.db.connectionPooler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "incident-commander.name" . }}-pgbouncer
  annotations:
{{ toYaml .Values.db.connectionPooler.serviceAccount.annotations | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incident-commander.name" . }}-pgbouncer
spec:
  selector:
    app: {{ include "incident-commander.name" . }}-pgbouncer
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-config
type: Opaque
data:
  pgbouncer.ini: W2RhdGFiYXNlc10NCm1pc3Npb25fY29udHJvbCA9IGhvc3Q9cG9zdGdyZXMubWlzc2lvbi1jb250cm9sLnN2Yy5jbHVzdGVyLmxvY2FsIHBvcnQ9NTQzMiBkYm5hbWU9bWlzc2lvbl9jb250cm9sDQoNCltwZ2JvdW5jZXJdDQpsaXN0ZW5fYWRkciA9IDAuMC4wLjANCmxpc3Rlbl9wb3J0ID0gNTQzMg0KdW5peF9zb2NrZXRfZGlyID0NCnVzZXIgPSBwb3N0Z3Jlcw0KYXV0aF9maWxlID0gL2V0Yy9wZ2JvdW5jZXIvdXNlcmxpc3QudHh0DQphdXRoX3R5cGUgPSBtZDUNCnBvb2xfbW9kZSA9IHRyYW5zYWN0aW9uDQptYXhfY2xpZW50X2Nvbm4gPSAxMDANCmlnbm9yZV9zdGFydHVwX3BhcmFtZXRlcnMgPSBleHRyYV9mbG9hdF9kaWdpdHMNCg0KIyBMb2cgc2V0dGluZ3MNCmFkbWluX3VzZXJzID0gcG9zdGdyZXM=
  userlist.txt: InBvc3RncmVzIiAiVWVHSmNaRDBIQ2hBUmVEY0lLd2VvOEpodXptdmdyU2IiDQoiYXBwX3VzZXIiICJhcHBwYXNzd29yZCI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-commander.name" . }}-pgbouncer
spec:
  selector:
    matchLabels:
      app: {{ include "incident-commander.name" . }}-pgbouncer
  template:
    metadata:
      labels:
        app: {{ include "incident-commander.name" . }}-pgbouncer
    spec:
      serviceAccountName: {{ include "incident-commander.name" . }}-pgbouncer
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer:1.21.0-p1
        ports:
        - containerPort: 5432
        env:
        - name: AUTH_TYPE
          value: md5
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretKeyRef.name }}
              key: POSTGRES_HOST
        - name: AUTH_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretKeyRef.name }}
              key: POSTGRES_USER
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretKeyRef.name }}
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretKeyRef.name }}
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretKeyRef.name }}
              key: DATABASE
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretKeyRef.name }}
              key: POSTGRES_PORT
{{ .Values.db.connectionPooler.extraContainers | indent 6 }}
---
{{- end }}