apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incident-commander.name" . }}-properties-config
  labels:
    {{- include "incident-commander.labels" . | nindent 4 }}
data:
  mission-control.properties: |
    {{- range $k, $v := .Values.properties }}
    {{ $k }}={{ $v }}
    {{- end }}
