{{- if .Values.serviceAccount.rbac.impersonate}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mission-control-read-namespaces
rules:
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mission-control-read-namespace-binding
subjects:
  - kind: User
    name: mission-control-reader
  - kind: User
    name: mission-control-writer
roleRef:
  kind: ClusterRole
  name: mission-control-read-namespaces
  apiGroup: rbac.authorization.k8s.io

{{- range .Values.impersonationRole.namespaces }}
{{- if and (ne . "kube-system") (ne . "mission-control") (ne . "kube-public") (ne . "kube-node-lease") }}

# We need to create namespaces for SaaS tenants
{{- if and (ne . "default") $.Values.impersonationRole.createNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.}}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mission-control-reader-role
  namespace: {{.}}
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['get', 'list', 'watch']
  - apiGroups:
      - 'configs.flanksource.com'
      - 'canaries.flanksource.com'
      - 'mission-control.flanksource.com'
    resources: ['*']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mission-control-crd-reader-role
rules:
  - apiGroups:
      - 'configs.flanksource.com'
      - 'canaries.flanksource.com'
      - 'mission-control.flanksource.com'
    resources: ['*']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mission-control-reader-role-binding
  namespace: {{.}}
subjects:
  - kind: User
    name: mission-control-reader
roleRef:
  kind: Role
  name: mission-control-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mission-control-crd-reader-role-binding
subjects:
  - kind: User
    name: mission-control-reader
roleRef:
  kind: Role
  name: mission-control-crd-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mission-control-writer-role
  namespace: {{.}}
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['*']
  - apiGroups:
      - 'configs.flanksource.com'
      - 'canaries.flanksource.com'
      - 'mission-control.flanksource.com'
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mission-control-crd-writer-role
rules:
  - apiGroups:
      - 'configs.flanksource.com'
      - 'canaries.flanksource.com'
      - 'mission-control.flanksource.com'
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mission-control-writer-role-binding
  namespace: {{.}}
subjects:
  - kind: User
    name: mission-control-writer
roleRef:
  kind: Role
  name: mission-control-writer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mission-control-crd-writer-role-binding
subjects:
  - kind: User
    name: mission-control-writer
roleRef:
  kind: Role
  name: mission-control-crd-writer-role
  apiGroup: rbac.authorization.k8s.io

{{- end}}
{{- end}}
{{- end}}
