{{- if .Values.artifactstore.enabled }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Connection
metadata:
  name: {{ .Values.artifactstore.connection.name | default "default-artifactstore" }}
spec:
  s3:
    accessKey:
      valueFrom:
        secretKeyRef:
          key: {{ .Values.artifactstore.secretKeyRef.key | default "ACCESS_KEY_ID" }}
          name: {{ .Values.artifactstore.secretKeyRef.name }}
    bucket: {{ .Values.artifactstore.connection.bucket | default "mission-control-artifacts" }}
    region: {{ .Values.artifactstore.connection.region | default "us-east-1" }}
    url:
      value: http://{{ include "incident-commander.artifactstore.name" . }}.{{ .Release.Namespace }}.svc:{{ .Values.artifactstore.service.port }}
    usePathStyle: {{ .Values.artifactstore.connection.usePathStyle | default true }}
    secretKey:
      valueFrom:
        secretKeyRef:
          key: SECRET_ACCESS_KEY
          name: {{ .Values.artifactstore.secretKeyRef.name }}
{{- end }}
  