{
 "title": "Mission Control Scrape Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "percentile",
    "query": "0.9,0.5,0.8,,0.95,0.97,0.98,0.99"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(go_goroutines{job=\"config-db\"})"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(1 - (go_memstats_heap_idle_bytes{job=\"config-db\"} / go_memstats_heap_sys_bytes{job=\"config-db\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"config-db\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"config-db\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"config-db\"}",
     "legendFormat": "Sys"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"config-db\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"config-db\"}",
     "legendFormat": "In Use"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"config-db\"}",
     "legendFormat": "Released"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(go_memstats_mallocs_total{job=\"config-db\"}[1m]))"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(go_memstats_alloc_bytes_total{job=\"config-db\"}[1m]))"
    }
   ]
  },
  {
   "title": "GC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (go_gc_duration_seconds{job=\"config-db\", quantile=\"1\"})"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(go_memstats_mallocs_total{job=\"config-db\"} - go_memstats_frees_total{job=\"config-db\"})"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Added",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kind) (increase(scraper_added[5m])) >0 ",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Updated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kind) (increase(scraper_updated[5m])) > 0   ",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Deleted (by config type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kind) (increase(scraper_deleted[5m])) > 0 ",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Deleted (by reason)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (reason) (increase(scraper_deleted[5m])) > 0 ",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Change Types",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by(change_type) (increase(config_changes[5m])) > 0\n",
       "legendFormat": "{{change_type}}"
      }
     ]
    },
    {
     "title": "Changes by kind",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
     "targets": [
      {
       "expr": "sum by(config_type) (increase(config_changes[5m])) > 0\n",
       "legendFormat": "{{config_type}}"
      }
     ]
    },
    {
     "title": "Changes by kind",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum by(config_type) (increase(config_changes[5m])) > 0\n",
       "legendFormat": "{{config_type}}"
      }
     ]
    },
    {
     "title": "Deduped ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (config_type) (increase(config_changes_deduped  [5m])) > 0",
       "legendFormat": "{{config_type}}"
      }
     ]
    },
    {
     "title": "Deduped by change",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (change_type) (increase(config_changes_deduped  [5m])) > 0",
       "legendFormat": "{{change_type}}"
      }
     ]
    },
    {
     "title": "Ignored by kind",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (kind) (increase(scraper_changes_ignored[5m])) > 0",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consume Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kind) (increase (informer_consume_lag_count[1m]) > 0)",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Consume - $percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by (kind) (histogram_quantile($percentile , informer_consume_lag_bucket))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Fetch Involved Objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by (kind) (histogram_quantile($percentile , involved_objects_enqueue_bucket))",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Received",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue (enqueued)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(kind) (increase(shared_informer_enqueued_total[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Queue (deduped)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(kind) (increase(shared_informer_deduped_total[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Queue (dequeued)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(kind) (increase(shared_informer_dequeued_total[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Queue duration - $percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max (histogram_quantile($percentile, shared_informer_duration_bucket))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Events (bad timestamps) (by kind)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(kind) (increase(kubernetes_informer_events{valid_timestamp=\"false\",type=\"update\"}[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Events (by operation)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(type) (increase(kubernetes_informer_events[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Events (by kind)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(kind) (increase(kubernetes_informer_events{valid_timestamp=\"true\"}[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Delete - $percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by (kind) (histogram_quantile($percentile, informer_receive_lag_bucket{operation=\"delete\"}))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Update - $percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by (kind) (histogram_quantile($percentile , informer_receive_lag_bucket{operation=\"update\"}))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Add - $percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by(kind) (histogram_quantile($percentile , informer_receive_lag_bucket{operation=\"add\"}))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Received - Operation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(operation) (increase(informer_receive_lag_count[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Received - Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 10, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(kind) (increase(informer_receive_lag_count[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Lookup - $percentile%",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max by (kind) (histogram_quantile($percentile , kubernetes_object_get_bucket))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Kubernetes Lookup Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (kind) (increase(kubernetes_object_get_count[5m])) > 0\n",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (scraper_id, scrape_type) (increase(temp_cache_hit[5m])) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Missing Hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "sum by (scrape_id) (increase(temp_cache_missing_hit[5m])) >0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "sum by (config_type) (increase(temp_cache_miss[5m])) >0 ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}